const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const D={players:["Αλέξανδρος","Παίκτης 2"],tic:{p1:0,p2:0},con:{p1:0,p2:0},flags:0,playersScore:0,teamsScore:0,wheel:["Φιλί","Μασάζ 10 λεπτά","Διαλέγει ταινία","Κερνάει καφέ","Διαλέγει τραγούδι","Κάνει μια χάρη"],coin:[],customPlayers:[],customTeams:[]};
let d=JSON.parse(localStorage.getItem("retroGamesDLemonis")||"null")||structuredClone(D);
const save=()=>{localStorage.setItem("retroGamesDLemonis",JSON.stringify(d));update()};
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1600)}
const meta={home:["RetroGames By D.Lemonis","Παιχνίδια για δύο στο ίδιο κινητό"],tic:["Τρίλιζα","Τρία σύμβολα στη σειρά"],connect:["Σκορ 4","Τέσσερα πιόνια στη σειρά"],hang:["Κρεμάλα","Μάντεψε τη λέξη"],coin:["Κορώνα–Γράμματα","Ρίξε το νόμισμα"],wheel:["Τροχός Τύχης","Challenges που αλλάζεις εσύ"],flags:["Σημαίες & Χώρες","Μάντεψε τη χώρα"],sports:["Αθλητισμός","Ποδοσφαιριστές και ομάδες"],stats:["Στατιστικά","Τα σκορ σας"],settings:["Ρυθμίσεις","Ονόματα παικτών"]};
function go(id){$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+id).classList.add("active");$("#title").textContent=meta[id][0];$("#subtitle").textContent=meta[id][1];$("#back").classList.toggle("hidden",id==="home");$("#settingsBtn").classList.toggle("hidden",id==="settings");scrollTo(0,0);if(id==="wheel")drawWheel();if(id==="flags")newFlag();if(id==="sports")newPlayer()}
$$("[data-screen]").forEach(b=>b.onclick=()=>go(b.dataset.screen));$("#back").onclick=()=>go("home");$("#settingsBtn").onclick=()=>go("settings");
function update(){let[a,b]=d.players;$("#p1Home").textContent=a;$("#p2Home").textContent=b;$("#ticN1").textContent=a;$("#ticN2").textContent=b;$("#conN1").textContent=a;$("#conN2").textContent=b;$("#ticS1").textContent=d.tic.p1;$("#ticS2").textContent=d.tic.p2;$("#conS1").textContent=d.con.p1;$("#conS2").textContent=d.con.p2;$("#p1Input").value=a;$("#p2Input").value=b;$("#flagScore").textContent=d.flags;$("#playerScore").textContent=d.playersScore;$("#teamScore").textContent=d.teamsScore;$("#stTic").textContent=d.tic.p1+"-"+d.tic.p2;$("#stCon").textContent=d.con.p1+"-"+d.con.p2;$("#stFlag").textContent=d.flags;$("#stPlayers").textContent=d.playersScore;renderWheel();renderCoin();renderCustom()}
$("#saveSettings").onclick=()=>{d.players=[$("#p1Input").value.trim()||"Παίκτης 1",$("#p2Input").value.trim()||"Παίκτης 2"];save();toast("Αποθηκεύτηκαν")};

let tb=Array(9).fill(""),tp="X",to=false;
function drawT(){let e=$("#ticBoard");e.innerHTML="";tb.forEach((v,i)=>{let b=document.createElement("button");b.className="tic-cell";b.textContent=v==="X"?"❌":v==="O"?"⭕":"";b.onclick=()=>{if(to||tb[i])return;tb[i]=tp;drawT();let w=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(a=>a.every(k=>tb[k]===tp));if(w){to=true;d.tic[tp==="X"?"p1":"p2"]++;$("#ticMsg").textContent="Νίκησε ο "+d.players[tp==="X"?0:1];save();return}if(tb.every(Boolean)){to=true;$("#ticMsg").textContent="Ισοπαλία";return}tp=tp==="X"?"O":"X";$("#ticTurn").textContent=tp==="X"?"❌":"⭕";$("#ticMsg").textContent="Παίζει ο "+d.players[tp==="X"?0:1]};e.append(b)})}
function resetT(){tb=Array(9).fill("");tp="X";to=false;$("#ticTurn").textContent="❌";$("#ticMsg").textContent="Παίζει ο "+d.players[0];drawT()}$("#ticNew").onclick=resetT;$("#ticReset").onclick=()=>{d.tic={p1:0,p2:0};save();resetT()};

let cb,p=1,co=false;
function drawC(){let e=$("#conBoard");e.innerHTML="";for(let r=0;r<6;r++)for(let c=0;c<7;c++){let b=document.createElement("button");b.className="con-cell"+(cb[r][c]===1?" r":cb[r][c]===2?" y":"");b.onclick=()=>moveC(c);e.append(b)}}
function resetC(){cb=Array.from({length:6},()=>Array(7).fill(0));p=1;co=false;$("#conTurn").textContent="🔴";$("#conMsg").textContent="Παίζει ο "+d.players[0];drawC()}
function moveC(c){if(co)return;let r=-1;for(let x=5;x>=0;x--)if(!cb[x][c]){r=x;break}if(r<0)return;cb[r][c]=p;drawC();if(winC(r,c)){co=true;d.con[p===1?"p1":"p2"]++;$("#conMsg").textContent="Νίκησε ο "+d.players[p-1];save();return}p=p===1?2:1;$("#conTurn").textContent=p===1?"🔴":"🟡";$("#conMsg").textContent="Παίζει ο "+d.players[p-1]}
function winC(r,c){for(let[a,b]of[[1,0],[0,1],[1,1],[1,-1]]){let n=1;for(let s of[-1,1]){let x=r+a*s,y=c+b*s;while(x>=0&&x<6&&y>=0&&y<7&&cb[x][y]===p){n++;x+=a*s;y+=b*s}}if(n>=4)return true}return false}$("#conNew").onclick=resetC;$("#conReset").onclick=()=>{d.con={p1:0,p2:0};save();resetC()};

const alpha="ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ";let word="",gu=new Set(),mis=0,hov=false;
const norm=s=>s.toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
$("#hangStart").onclick=()=>{word=norm($("#secret").value.trim());if(word.length<2)return toast("Γράψε λέξη");gu=new Set();mis=0;hov=false;$("#hangSetup").classList.add("hidden");$("#hangPlay").classList.remove("hidden");renderH()};
function renderH(){let f=["🙂","😐","😟","😨","😵","💀","☠️"];$("#hangFace").textContent=f[mis];$("#mistakes").textContent=mis;$("#hintOut").textContent=$("#hint").value?"Βοήθεια: "+$("#hint").value:"";$("#wordOut").textContent=[...word].map(c=>/[^Α-ΩA-Z]/.test(c)||gu.has(c)?c:"_").join(" ");$("#wrongOut").textContent=[...gu].filter(c=>!word.includes(c)).join(" ");let k=$("#keyboard");k.innerHTML="";[...alpha].forEach(l=>{let b=document.createElement("button");b.textContent=l;b.disabled=gu.has(l)||hov;b.onclick=()=>{gu.add(l);if(!word.includes(l))mis++;let won=[...word].filter(c=>/[Α-ΩA-Z]/.test(c)).every(c=>gu.has(c));if(won){hov=true;$("#hangMsg").textContent="Βρήκες τη λέξη"}else if(mis>=6){hov=true;$("#hangMsg").textContent="Η λέξη ήταν "+word}renderH()};k.append(b)})}$("#hangNew").onclick=()=>{$("#secret").value="";$("#hint").value="";$("#hangSetup").classList.remove("hidden");$("#hangPlay").classList.add("hidden")};

$("#flipCoin").onclick=()=>{let c=$("#coinDisc");c.classList.remove("flip");void c.offsetWidth;c.classList.add("flip");setTimeout(()=>{let r=Math.random()<.5?"Κορώνα":"Γράμματα";c.textContent=r==="Κορώνα"?"👑":"🔤";$("#coinResult").textContent=r;d.coin.unshift(r);d.coin=d.coin.slice(0,20);save()},850)};
function renderCoin(){$("#coinHistory").innerHTML=d.coin.length?d.coin.map((x,i)=>"<div class='custom-row'><span>"+(i+1)+". "+x+"</span></div>").join(""):"Δεν υπάρχουν ρίψεις."}

let ang=0,spin=false;const cols=["#ef4444","#f59e0b","#10b981","#06b6d4","#3b82f6","#8b5cf6","#ec4899","#64748b"];
function drawWheel(){let c=$("#wheelCanvas"),x=c.getContext("2d"),n=d.wheel.length||1;x.clearRect(0,0,700,700);for(let i=0;i<n;i++){let a=ang+i*2*Math.PI/n,b=ang+(i+1)*2*Math.PI/n;x.beginPath();x.moveTo(350,350);x.arc(350,350,330,a,b);x.fillStyle=cols[i%cols.length];x.fill();x.save();x.translate(350,350);x.rotate((a+b)/2);x.textAlign="right";x.fillStyle="white";x.font="bold 25px sans-serif";x.fillText(d.wheel[i].slice(0,21),305,8);x.restore()}x.beginPath();x.arc(350,350,50,0,Math.PI*2);x.fillStyle="white";x.fill()}
$("#spinWheel").onclick=()=>{if(spin||d.wheel.length<2)return;spin=true;let st=ang,ex=Math.PI*2*(5+Math.random()*4),t0=performance.now();function a(t){let q=Math.min(1,(t-t0)/3500);ang=st+ex*(1-Math.pow(1-q,3));drawWheel();if(q<1)requestAnimationFrame(a);else{spin=false;let n=d.wheel.length,v=(((-Math.PI/2-ang)%(Math.PI*2))+Math.PI*2)%(Math.PI*2),i=Math.floor(v/(Math.PI*2/n));$("#wheelResult").textContent=d.wheel[i]}}requestAnimationFrame(a)};
$("#addWheel").onclick=()=>{let v=$("#wheelInput").value.trim();if(!v)return;d.wheel.push(v);$("#wheelInput").value="";save();drawWheel()};
function renderWheel(){let e=$("#wheelItems");e.innerHTML="";d.wheel.forEach((v,i)=>{let r=document.createElement("div"),s=document.createElement("span"),ed=document.createElement("button"),del=document.createElement("button");s.textContent=v;ed.textContent="✏️";del.textContent="🗑️";ed.onclick=()=>{let nv=prompt("Αλλαγή",v);if(nv){d.wheel[i]=nv;save();drawWheel()}};del.onclick=()=>{if(d.wheel.length<=2)return toast("Χρειάζονται 2 επιλογές");d.wheel.splice(i,1);save();drawWheel()};r.append(s,ed,del);e.append(r)})}

const flags=[["🇬🇷","Ελλάδα"],["🇮🇹","Ιταλία"],["🇪🇸","Ισπανία"],["🇫🇷","Γαλλία"],["🇩🇪","Γερμανία"],["🇵🇹","Πορτογαλία"],["🇧🇷","Βραζιλία"],["🇦🇷","Αργεντινή"],["🇬🇧","Ηνωμένο Βασίλειο"],["🇺🇸","ΗΠΑ"],["🇯🇵","Ιαπωνία"],["🇨🇳","Κίνα"],["🇨🇦","Καναδάς"],["🇦🇺","Αυστραλία"],["🇲🇽","Μεξικό"],["🇳🇱","Ολλανδία"],["🇧🇪","Βέλγιο"],["🇭🇷","Κροατία"],["🇹🇷","Τουρκία"],["🇨🇾","Κύπρος"]];
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function options(box,names,correct,cb){box.innerHTML="";names.forEach(n=>{let b=document.createElement("button");b.textContent=n;b.onclick=()=>{[...box.children].forEach(x=>x.disabled=true);b.classList.add(n===correct?"correct":"wrong");cb(n)};box.append(b)})}
function newFlag(){let q=flags[Math.floor(Math.random()*flags.length)];$("#flagEmoji").textContent=q[0];$("#flagMsg").textContent="";let o=shuffle([q,...shuffle(flags.filter(x=>x!==q)).slice(0,3)]).map(x=>x[1]);options($("#flagOptions"),o,q[1],a=>{if(a===q[1]){d.flags++;save();$("#flagMsg").textContent="Σωστά"}else $("#flagMsg").textContent="Η σωστή απάντηση είναι "+q[1]})}$("#nextFlag").onclick=newFlag;

const players=[{name:"Lionel Messi",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Lionel_Messi_in_2018.jpg"},{name:"Cristiano Ronaldo",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Cristiano_Ronaldo_2018.jpg"},{name:"Kylian Mbappé",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Kylian_Mbapp%C3%A9.jpg"},{name:"Erling Haaland",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Erling_Haaland_2023_%28cropped%29.jpg"},{name:"Neymar",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Neymar_Jr._with_Al_Hilal%2C_3_October_2023_-_03_%28cropped%29.jpg"},{name:"Mohamed Salah",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Mohamed_Salah_2018.jpg"}];
const teams=[{name:"Barcelona",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/FC_Barcelona_%28crest%29.svg"},{name:"Real Madrid",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Real_Madrid_CF.svg"},{name:"Liverpool",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Liverpool_FC.svg"},{name:"Manchester United",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Manchester_United_FC_crest.svg"}];
function setImg(img,fb,url){fb.style.display="none";img.style.display="block";img.onerror=()=>{img.style.display="none";fb.style.display="grid"};img.src=url}
function newPlayer(){let all=[...players,...d.customPlayers],q=all[Math.floor(Math.random()*all.length)];setImg($("#playerImg"),$("#playerFallback"),q.img);$("#playerMsg").textContent="";let o=shuffle([q,...shuffle(all.filter(x=>x!==q)).slice(0,3)]).map(x=>x.name);options($("#playerOptions"),o,q.name,a=>{if(a===q.name){d.playersScore++;save();$("#playerMsg").textContent="Σωστά"}else $("#playerMsg").textContent="Ήταν ο "+q.name})}
function newTeam(){let all=[...teams,...d.customTeams],q=all[Math.floor(Math.random()*all.length)];setImg($("#teamImg"),$("#teamFallback"),q.img);$("#teamMsg").textContent="";let o=shuffle([q,...shuffle(all.filter(x=>x!==q)).slice(0,3)]).map(x=>x.name);options($("#teamOptions"),o,q.name,a=>{if(a===q.name){d.teamsScore++;save();$("#teamMsg").textContent="Σωστά"}else $("#teamMsg").textContent="Ήταν η "+q.name})}
$("#nextPlayer").onclick=newPlayer;$("#nextTeam").onclick=newTeam;$$(".tab").forEach(b=>b.onclick=()=>{$$(".tab").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".pane").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.pane).classList.add("active");if(b.dataset.pane==="teamsPane")newTeam()});
function fileData(f,cb){let r=new FileReader();r.onload=()=>cb(r.result);r.readAsDataURL(f)}
$("#addPlayer").onclick=()=>{let n=$("#newPlayerName").value.trim(),f=$("#newPlayerPhoto").files[0];if(!n||!f)return toast("Βάλε όνομα και φωτογραφία");fileData(f,img=>{d.customPlayers.push({name:n,img});try{save();toast("Προστέθηκε")}catch{d.customPlayers.pop();toast("Μεγάλη φωτογραφία")}})};
$("#addTeam").onclick=()=>{let n=$("#newTeamName").value.trim(),f=$("#newTeamPhoto").files[0];if(!n||!f)return toast("Βάλε όνομα και λογότυπο");fileData(f,img=>{d.customTeams.push({name:n,img});try{save();toast("Προστέθηκε")}catch{d.customTeams.pop();toast("Μεγάλη φωτογραφία")}})};
function renderCustom(){let e=$("#customList");e.innerHTML="";[...d.customPlayers.map((x,i)=>({t:"Παίκτης",x,i,k:"customPlayers"})),...d.customTeams.map((x,i)=>({t:"Ομάδα",x,i,k:"customTeams"}))].forEach(o=>{let r=document.createElement("div");r.className="custom-row";let s=document.createElement("span");s.textContent=o.t+": "+o.x.name;let b=document.createElement("button");b.textContent="🗑️";b.onclick=()=>{d[o.k].splice(o.i,1);save()};r.append(s,b);e.append(r)});if(!e.children.length)e.textContent="Δεν υπάρχουν δικές σου προσθήκες."}

if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));update();resetT();resetC();drawWheel();