const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const D={players:["Αλέξανδρος","Παίκτης 2"],tic:{p1:0,p2:0},con:{p1:0,p2:0},flags:0,playersScore:0,teamsScore:0,wheel:["Φιλί","Μασάζ 10 λεπτά","Διαλέγει ταινία","Κερνάει καφέ","Διαλέγει τραγούδι","Κάνει μια χάρη"],coin:[],customPlayers:[],customTeams:[]};
let d=JSON.parse(localStorage.getItem("retroGamesDLemonis")||"null")||structuredClone(D);
const save=()=>{localStorage.setItem("retroGamesDLemonis",JSON.stringify(d));update()};
function toast(t){let e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),1600)}
const meta={home:["RetroGames By D.Lemonis",""],tic:["Τρίλιζα","Τρία σύμβολα στη σειρά"],connect:["Σκορ 4","Τέσσερα πιόνια στη σειρά"],hang:["Κρεμάλα","Μάντεψε τη λέξη"],coin:["Κορώνα–Γράμματα","Ρίξε το νόμισμα"],wheel:["Τροχός Τύχης","Challenges που αλλάζεις εσύ"],flags:["Σημαίες & Χώρες","Μάντεψε τη χώρα"],sports:["Αθλητισμός","Ποδοσφαιριστές και ομάδες"],stats:["Στατιστικά","Τα σκορ σας"],settings:["Ρυθμίσεις","Ονόματα παικτών"]};
function go(id){$$('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$('#title').textContent=meta[id][0];$('#subtitle').textContent=meta[id][1]||'';$('#subtitle').classList.toggle('hidden',!meta[id][1]);$('#back').classList.toggle('hidden',id==='home');$('#settingsBtn').classList.toggle('hidden',id==='settings');scrollTo(0,0);if(id==='wheel')drawWheel();if(id==='flags')newFlag();if(id==='sports')showSportsStart()}
$$('[data-screen]').forEach(b=>b.onclick=()=>go(b.dataset.screen));$("#back").onclick=()=>go("home");$("#settingsBtn").onclick=()=>go("settings");
function update(){let[a,b]=d.players;$("#p1Home").textContent=a;$("#p2Home").textContent=b;$("#ticN1").textContent=a;$("#ticN2").textContent=b;$("#conN1").textContent=a;$("#conN2").textContent=b;$("#ticS1").textContent=d.tic.p1;$("#ticS2").textContent=d.tic.p2;$("#conS1").textContent=d.con.p1;$("#conS2").textContent=d.con.p2;$("#p1Input").value=a;$("#p2Input").value=b;$("#flagScore").textContent=d.flags;$("#playerScore").textContent=d.playersScore;$("#teamScore").textContent=d.teamsScore;$("#stTic").textContent=d.tic.p1+"-"+d.tic.p2;$("#stCon").textContent=d.con.p1+"-"+d.con.p2;$("#stFlag").textContent=d.flags;$("#stPlayers").textContent=d.playersScore;renderWheel();renderCoin();renderCustom()}
$("#saveSettings").onclick=()=>{d.players=[$("#p1Input").value.trim()||"Παίκτης 1",$("#p2Input").value.trim()||"Παίκτης 2"];save();toast("Αποθηκεύτηκαν")};

let tb=Array(9).fill(""),tp="X",to=false;
function drawT(){let e=$("#ticBoard");e.innerHTML="";tb.forEach((v,i)=>{let b=document.createElement("button");b.className="tic-cell";b.textContent=v==="X"?"❌":v==="O"?"⭕":"";b.onclick=()=>{if(to||tb[i])return;tb[i]=tp;drawT();let w=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(a=>a.every(k=>tb[k]===tp));if(w){to=true;d.tic[tp==="X"?"p1":"p2"]++;$("#ticMsg").textContent="Νίκησε ο "+d.players[tp==="X"?0:1];save();return}if(tb.every(Boolean)){to=true;$("#ticMsg").textContent="Ισοπαλία";return}tp=tp==="X"?"O":"X";$("#ticTurn").textContent=tp==="X"?"❌":"⭕";$("#ticMsg").textContent="Παίζει ο "+d.players[tp==="X"?0:1]};e.append(b)})}
function resetT(){tb=Array(9).fill("");tp="X";to=false;$("#ticTurn").textContent="❌";$("#ticMsg").textContent="Παίζει ο "+d.players[0];drawT()}$("#ticNew").onclick=resetT;$("#ticReset").onclick=()=>{d.tic={p1:0,p2:0};save();resetT()};

let cb,p=1,co=false;
function drawC(){let e=$("#conBoard");e.innerHTML="";for(let r=0;r<6;r++)for(let c=0;c<7;c++){let b=document.createElement("button");b.className="con-cell"+(cb[r][c]===1?" r":cb[r][c]===2?" y":"");b.onclick=()=>moveC(c);e.append(b)}}
function resetC(){cb=Array.from({length:6},()=>Array(7).fill(0));p=1;co=false;$("#conTurn").textContent="🔴";$("#conMsg").textContent="Παίζει ο "+d.players[0];drawC()}
function moveC(c){if(co)return;let r=-1;for(let x=5;x>=0;x--)if(!cb[x][c]){r=x;break}if(r<0)return;cb[r][c]=p;drawC();if(winC(r,c)){co=true;d.con[p===1?"p1":"p2"]++;$("#conMsg").textContent="Νίκησε ο "+d.players[p-1];save();return}p=p===1?2:1;$("#conTurn").textContent=p===1?"🔴":"🟡";$("#conMsg").textContent="Παίζει ο "+d.players[p-1]}
function winC(r,c){for(let[a,b]of[[1,0],[0,1],[1,1],[1,-1]]){let n=1;for(let s of[-1,1]){let x=r+a*s,y=c+b*s;while(x>=0&&x<6&&y>=0&&y<7&&cb[x][y]===p){n++;x+=a*s;y+=b*s}}if(n>=4)return true}return false}$("#conNew").onclick=resetC;$("#conReset").onclick=()=>{d.con={p1:0,p2:0};save();resetC()};

const alpha="ΑΒΓΔΕΖΗΘΙΚΛΜΝΞΟΠΡΣΤΥΦΧΨΩ";let word="",gu=new Set(),mis=0,hov=false;
const norm=s=>s.toUpperCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"");
$("#hangStart").onclick=()=>{word=norm($("#secret").value.trim());if(word.length<2)return toast("Γράψε λέξη");gu=new Set();mis=0;hov=false;$("#hangSetup").classList.add("hidden");$("#hangPlay").classList.remove("hidden");renderH()};
function renderH(){let f=["🙂","😐","😟","😨","😵","💀","☠️"];$("#hangFace").textContent=f[mis];$("#mistakes").textContent=mis;$("#hintOut").textContent=$("#hint").value?"Βοήθεια: "+$("#hint").value:"";$("#wordOut").textContent=[...word].map(c=>/[^Α-ΩA-Z]/.test(c)||gu.has(c)?c:"_").join(" ");$("#wrongOut").textContent=[...gu].filter(c=>!word.includes(c)).join(" ");let k=$("#keyboard");k.innerHTML="";[...alpha].forEach(l=>{let b=document.createElement("button");b.textContent=l;b.disabled=gu.has(l)||hov;b.onclick=()=>{gu.add(l);if(!word.includes(l))mis++;let won=[...word].filter(c=>/[Α-ΩA-Z]/.test(c)).every(c=>gu.has(c));if(won){hov=true;$("#hangMsg").textContent="Βρήκες τη λέξη"}else if(mis>=6){hov=true;$("#hangMsg").textContent="Η λέξη ήταν "+word}renderH()};k.append(b)})}$("#hangNew").onclick=()=>{$("#secret").value="";$("#hint").value="";$("#hangSetup").classList.remove("hidden");$("#hangPlay").classList.add("hidden")};

$("#flipCoin").onclick=()=>{let c=$("#coinDisc");c.classList.remove("flip");void c.offsetWidth;c.classList.add("flip");setTimeout(()=>{let r=Math.random()<.5?"Κορώνα":"Γράμματα";c.textContent=r==="Κορώνα"?"👑":"🔤";$("#coinResult").textContent=r;d.coin.unshift(r);d.coin=d.coin.slice(0,20);save()},850)};
function renderCoin(){$("#coinHistory").innerHTML=d.coin.length?d.coin.map((x,i)=>"<div class='custom-row'><span>"+(i+1)+". "+x+"</span></div>").join(""):"Δεν υπάρχουν ρίψεις."}

let ang=0,spin=false;const cols=["#ef4444","#f59e0b","#10b981","#06b6d4","#3b82f6","#8b5cf6","#ec4899","#64748b"];
function drawWheel(){let c=$("#wheelCanvas"),x=c.getContext("2d"),n=d.wheel.length||1;x.clearRect(0,0,700,700);for(let i=0;i<n;i++){let a=ang+i*2*Math.PI/n,b=ang+(i+1)*2*Math.PI/n;x.beginPath();x.moveTo(350,350);x.arc(350,350,330,a,b);x.fillStyle=cols[i%cols.length];x.fill();x.save();x.translate(350,350);x.rotate((a+b)/2);x.textAlign="right";x.fillStyle="white";x.font="bold 25px sans-serif";x.fillText(d.wheel[i].slice(0,21),305,8);x.restore()}x.beginPath();x.arc(350,350,50,0,Math.PI*2);x.fillStyle="white";x.fill()}
$("#spinWheel").onclick=()=>{if(spin||d.wheel.length<2)return;spin=true;let st=ang,ex=Math.PI*2*(5+Math.random()*4),t0=performance.now();function a(t){let q=Math.min(1,(t-t0)/3500);ang=st+ex*(1-Math.pow(1-q,3));drawWheel();if(q<1)requestAnimationFrame(a);else{spin=false;let n=d.wheel.length,v=(((-Math.PI/2-ang)%(Math.PI*2))+Math.PI*2)%(Math.PI*2),i=Math.floor(v/(Math.PI*2/n));$("#wheelResult").textContent=d.wheel[i]}}requestAnimationFrame(a)};
$("#addWheel").onclick=()=>{let v=$("#wheelInput").value.trim();if(!v)return;d.wheel.push(v);$("#wheelInput").value="";save();drawWheel()};
function renderWheel(){let e=$("#wheelItems");e.innerHTML="";d.wheel.forEach((v,i)=>{let r=document.createElement("div"),s=document.createElement("span"),ed=document.createElement("button"),del=document.createElement("button");s.textContent=v;ed.textContent="✏️";del.textContent="🗑️";ed.onclick=()=>{let nv=prompt("Αλλαγή",v);if(nv){d.wheel[i]=nv;save();drawWheel()}};del.onclick=()=>{if(d.wheel.length<=2)return toast("Χρειάζονται 2 επιλογές");d.wheel.splice(i,1);save();drawWheel()};r.append(s,ed,del);e.append(r)})}

const flags=[["🇬🇷","Ελλάδα"],["🇮🇹","Ιταλία"],["🇪🇸","Ισπανία"],["🇫🇷","Γαλλία"],["🇩🇪","Γερμανία"],["🇵🇹","Πορτογαλία"],["🇧🇷","Βραζιλία"],["🇦🇷","Αργεντινή"],["🇬🇧","Ηνωμένο Βασίλειο"],["🇺🇸","ΗΠΑ"],["🇯🇵","Ιαπωνία"],["🇨🇳","Κίνα"],["🇨🇦","Καναδάς"],["🇦🇺","Αυστραλία"],["🇲🇽","Μεξικό"],["🇳🇱","Ολλανδία"],["🇧🇪","Βέλγιο"],["🇭🇷","Κροατία"],["🇹🇷","Τουρκία"],["🇨🇾","Κύπρος"]];
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function options(box,names,correct,cb){box.innerHTML="";names.forEach(n=>{let b=document.createElement("button");b.textContent=n;b.onclick=()=>{[...box.children].forEach(x=>x.disabled=true);b.classList.add(n===correct?"correct":"wrong");cb(n)};box.append(b)})}
function newFlag(){let q=flags[Math.floor(Math.random()*flags.length)];$("#flagEmoji").textContent=q[0];$("#flagMsg").textContent="";let o=shuffle([q,...shuffle(flags.filter(x=>x!==q)).slice(0,3)]).map(x=>x[1]);options($("#flagOptions"),o,q[1],a=>{if(a===q[1]){d.flags++;save();$("#flagMsg").textContent="Σωστά"}else $("#flagMsg").textContent="Η σωστή απάντηση είναι "+q[1]})}$("#nextFlag").onclick=newFlag;

function commons(file){
  const normalized=file.replace(/ /g,"_");
  let h=md5(normalized);
  return `https://upload.wikimedia.org/wikipedia/commons/${h[0]}/${h.slice(0,2)}/${encodeURIComponent(normalized).replace(/%2F/g,"/")}`;
}
/* Μικρή υλοποίηση MD5 μόνο για τη δημιουργία σταθερών Wikimedia URLs */
function md5(str){function cmn(q,a,b,x,s,t){a=(a+q+x+t)|0;return (((a<<s)|(a>>>(32-s)))+b)|0}function ff(a,b,c,d,x,s,t){return cmn((b&c)|((~b)&d),a,b,x,s,t)}function gg(a,b,c,d,x,s,t){return cmn((b&d)|(c&(~d)),a,b,x,s,t)}function hh(a,b,c,d,x,s,t){return cmn(b^c^d,a,b,x,s,t)}function ii(a,b,c,d,x,s,t){return cmn(c^(b|(~d)),a,b,x,s,t)}function cycle(x,k){let a=x[0],b=x[1],c=x[2],d=x[3];a=ff(a,b,c,d,k[0],7,-680876936);d=ff(d,a,b,c,k[1],12,-389564586);c=ff(c,d,a,b,k[2],17,606105819);b=ff(b,c,d,a,k[3],22,-1044525330);a=ff(a,b,c,d,k[4],7,-176418897);d=ff(d,a,b,c,k[5],12,1200080426);c=ff(c,d,a,b,k[6],17,-1473231341);b=ff(b,c,d,a,k[7],22,-45705983);a=ff(a,b,c,d,k[8],7,1770035416);d=ff(d,a,b,c,k[9],12,-1958414417);c=ff(c,d,a,b,k[10],17,-42063);b=ff(b,c,d,a,k[11],22,-1990404162);a=ff(a,b,c,d,k[12],7,1804603682);d=ff(d,a,b,c,k[13],12,-40341101);c=ff(c,d,a,b,k[14],17,-1502002290);b=ff(b,c,d,a,k[15],22,1236535329);a=gg(a,b,c,d,k[1],5,-165796510);d=gg(d,a,b,c,k[6],9,-1069501632);c=gg(c,d,a,b,k[11],14,643717713);b=gg(b,c,d,a,k[0],20,-373897302);a=gg(a,b,c,d,k[5],5,-701558691);d=gg(d,a,b,c,k[10],9,38016083);c=gg(c,d,a,b,k[15],14,-660478335);b=gg(b,c,d,a,k[4],20,-405537848);a=gg(a,b,c,d,k[9],5,568446438);d=gg(d,a,b,c,k[14],9,-1019803690);c=gg(c,d,a,b,k[3],14,-187363961);b=gg(b,c,d,a,k[8],20,1163531501);a=gg(a,b,c,d,k[13],5,-1444681467);d=gg(d,a,b,c,k[2],9,-51403784);c=gg(c,d,a,b,k[7],14,1735328473);b=gg(b,c,d,a,k[12],20,-1926607734);a=hh(a,b,c,d,k[5],4,-378558);d=hh(d,a,b,c,k[8],11,-2022574463);c=hh(c,d,a,b,k[11],16,1839030562);b=hh(b,c,d,a,k[14],23,-35309556);a=hh(a,b,c,d,k[1],4,-1530992060);d=hh(d,a,b,c,k[4],11,1272893353);c=hh(c,d,a,b,k[7],16,-155497632);b=hh(b,c,d,a,k[10],23,-1094730640);a=hh(a,b,c,d,k[13],4,681279174);d=hh(d,a,b,c,k[0],11,-358537222);c=hh(c,d,a,b,k[3],16,-722521979);b=hh(b,c,d,a,k[6],23,76029189);a=hh(a,b,c,d,k[9],4,-640364487);d=hh(d,a,b,c,k[12],11,-421815835);c=hh(c,d,a,b,k[15],16,530742520);b=hh(b,c,d,a,k[2],23,-995338651);a=ii(a,b,c,d,k[0],6,-198630844);d=ii(d,a,b,c,k[7],10,1126891415);c=ii(c,d,a,b,k[14],15,-1416354905);b=ii(b,c,d,a,k[5],21,-57434055);a=ii(a,b,c,d,k[12],6,1700485571);d=ii(d,a,b,c,k[3],10,-1894986606);c=ii(c,d,a,b,k[10],15,-1051523);b=ii(b,c,d,a,k[1],21,-2054922799);a=ii(a,b,c,d,k[8],6,1873313359);d=ii(d,a,b,c,k[15],10,-30611744);c=ii(c,d,a,b,k[6],15,-1560198380);b=ii(b,c,d,a,k[13],21,1309151649);a=ii(a,b,c,d,k[4],6,-145523070);d=ii(d,a,b,c,k[11],10,-1120210379);c=ii(c,d,a,b,k[2],15,718787259);b=ii(b,c,d,a,k[9],21,-343485551);x[0]=(a+x[0])|0;x[1]=(b+x[1])|0;x[2]=(c+x[2])|0;x[3]=(d+x[3])|0}function blk(s){let n=s.length*8,a=[];for(let i=0;i<n;i+=8)a[i>>5]|=(s.charCodeAt(i/8)&255)<<(i%32);a[n>>5]|=128<<(n%32);a[(((n+64)>>>9)<<4)+14]=n;return a}let x=[1732584193,-271733879,-1732584194,271733878],a=blk(unescape(encodeURIComponent(str)));for(let i=0;i<a.length;i+=16)cycle(x,a.slice(i,i+16));return x.map(v=>[0,8,16,24].map(s=>(v>>>s&255).toString(16).padStart(2,"0")).join("")).join("")}

const players=[
{name:"Lionel Messi",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Lionel_Messi_in_2018.jpg"},
{name:"Cristiano Ronaldo",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Cristiano_Ronaldo_2018.jpg"},
{name:"Kylian Mbappé",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Kylian_Mbapp%C3%A9.jpg"},
{name:"Erling Haaland",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Erling_Haaland_2023_%28cropped%29.jpg"},
{name:"Neymar",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Neymar_Jr._with_Al_Hilal%2C_3_October_2023_-_03_%28cropped%29.jpg"},
{name:"Mohamed Salah",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Mohamed_Salah_2018.jpg"},
{name:"Luka Modrić",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Luka_Modric_2018.jpg"},
{name:"Robert Lewandowski",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Robert_Lewandowski_2018.jpg"},
{name:"Kevin De Bruyne",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Kevin_De_Bruyne_201807091.jpg"},
{name:"Harry Kane",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Harry_Kane_2018.jpg"},
{name:"Vinícius Júnior",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Vinicius_Jr_2021.jpg"},
{name:"Jude Bellingham",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Jude_Bellingham_2023.jpg"},
{name:"Antoine Griezmann",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Antoine_Griezmann_2018.jpg"},
{name:"Sergio Ramos",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Sergio_Ramos_2018.jpg"},
{name:"Manuel Neuer",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Manuel_Neuer_2018.jpg"},
{name:"Zlatan Ibrahimović",img:"https://commons.wikimedia.org/wiki/Special:Redirect/file/Zlatan_Ibrahimovi%C4%87_June_2018.jpg"}
];
const teams=[
{name:"Barcelona",img:"assets/teams/barcelona.svg"},{name:"Real Madrid",img:"assets/teams/real-madrid.svg"},{name:"Liverpool",img:"assets/teams/liverpool.svg"},{name:"Manchester United",img:"assets/teams/manchester-united.svg"},{name:"Arsenal",img:"assets/teams/arsenal.svg"},{name:"Juventus",img:"assets/teams/juventus.svg"},{name:"Bayern Munich",img:"assets/teams/bayern.svg"},{name:"Paris Saint-Germain",img:"assets/teams/psg.svg"},{name:"Inter",img:"assets/teams/inter.svg"},{name:"Chelsea",img:"assets/teams/chelsea.svg"},{name:"Manchester City",img:"assets/teams/man-city.svg"},{name:"Milan",img:"assets/teams/milan.svg"},{name:"Borussia Dortmund",img:"assets/teams/dortmund.svg"},{name:"Ajax",img:"assets/teams/ajax.svg"},{name:"Olympiacos",img:"assets/teams/olympiacos.svg"},{name:"Panathinaikos",img:"assets/teams/panathinaikos.svg"},{name:"AEK",img:"assets/teams/aek.svg"},{name:"PAOK",img:"assets/teams/paok.svg"}
];
function setImg(img,fb,url){fb.style.display='none';img.style.display='block';img.onload=()=>{fb.style.display='none';img.style.display='block'};img.onerror=()=>{img.style.display='none';fb.style.display='grid'};img.src=url}
let playerBag=[],teamBag=[],lastPlayer='',lastTeam='';
function nextFromBag(all,kind){let bag=kind==='player'?playerBag:teamBag,last=kind==='player'?lastPlayer:lastTeam;if(!bag.length){bag=shuffle(all.map((_,i)=>i));if(bag.length>1&&all[bag[0]].name===last)bag.push(bag.shift());if(kind==='player')playerBag=bag;else teamBag=bag}let i=bag.shift();if(kind==='player')lastPlayer=all[i].name;else lastTeam=all[i].name;return all[i]}
let sportsState={type:'players',count:1,names:['Παίκτης 1'],scores:[0],turn:0,answered:false};
function renderSportsNames(){let count=Number($('#sportsPlayerCount').value),box=$('#sportsNames');box.innerHTML='';for(let i=0;i<count;i++){let lab=document.createElement('label');lab.textContent='Όνομα παίκτη '+(i+1);let inp=document.createElement('input');inp.id='sportsName'+i;inp.value=(d.players&&d.players[i])||('Παίκτης '+(i+1));lab.append(inp);box.append(lab)}}
$('#sportsPlayerCount').onchange=renderSportsNames;
function showSportsStart(){$('#sportsStart').classList.remove('hidden');$('#sportsGame').classList.add('hidden');$('#addPane').classList.add('hidden');renderSportsNames()}
$('#startSportsGame').onclick=()=>{let count=Number($('#sportsPlayerCount').value),names=[];for(let i=0;i<count;i++)names.push(($('#sportsName'+i).value||'Παίκτης '+(i+1)).trim());sportsState={type:$('#sportsGameType').value,count,names,scores:Array(count).fill(0),turn:0,answered:false};$('#sportsStart').classList.add('hidden');$('#addPane').classList.add('hidden');$('#sportsGame').classList.remove('hidden');$('#playersPane').classList.toggle('active',sportsState.type==='players');$('#teamsPane').classList.toggle('active',sportsState.type==='teams');renderSportsScore();sportsState.type==='players'?newPlayer():newTeam()};
$('#endSportsGame').onclick=showSportsStart;
$('#openSportsAdd').onclick=()=>{$('#sportsStart').classList.add('hidden');$('#sportsGame').classList.add('hidden');$('#addPane').classList.remove('hidden');renderCustom()};
$('#backFromAdd').onclick=showSportsStart;
function renderSportsScore(){$('#sportsTurnName').textContent=sportsState.names[sportsState.turn];$('#sportsScoreboard').innerHTML=sportsState.names.map((n,i)=>`<span class="${i===sportsState.turn?'active':''}"><small>${n}</small><b>${sportsState.scores[i]}</b></span>`).join('')}
function advanceSportsTurn(){sportsState.turn=(sportsState.turn+1)%sportsState.count;renderSportsScore()}
function newPlayer(){let all=[...players,...d.customPlayers];if(all.length<4)return toast('Χρειάζονται τουλάχιστον 4 ποδοσφαιριστές');sportsState.answered=false;let q=nextFromBag(all,'player');setImg($('#playerImg'),$('#playerFallback'),q.img);$('#playerMsg').textContent='';let o=shuffle([q,...shuffle(all.filter(x=>x!==q&&x.name!==q.name)).slice(0,3)]).map(x=>x.name);options($('#playerOptions'),o,q.name,a=>{if(sportsState.answered)return;sportsState.answered=true;if(a===q.name){sportsState.scores[sportsState.turn]++;$('#playerMsg').textContent='Σωστά! 🎉'}else $('#playerMsg').textContent='Ήταν ο '+q.name;renderSportsScore()})}
function newTeam(){let all=[...teams,...d.customTeams];if(all.length<4)return toast('Χρειάζονται τουλάχιστον 4 σήματα');sportsState.answered=false;let q=nextFromBag(all,'team');setImg($('#teamImg'),$('#teamFallback'),q.img);$('#teamMsg').textContent='';let o=shuffle([q,...shuffle(all.filter(x=>x!==q&&x.name!==q.name)).slice(0,3)]).map(x=>x.name);options($('#teamOptions'),o,q.name,a=>{if(sportsState.answered)return;sportsState.answered=true;if(a===q.name){sportsState.scores[sportsState.turn]++;$('#teamMsg').textContent='Σωστά! 🎉'}else $('#teamMsg').textContent='Ήταν το σήμα της '+q.name;renderSportsScore()})}
$('#nextPlayer').onclick=()=>{advanceSportsTurn();newPlayer()};$('#nextTeam').onclick=()=>{advanceSportsTurn();newTeam()};
function compressFile(file,max=900,quality=.78){return new Promise((resolve,reject)=>{let r=new FileReader();r.onerror=reject;r.onload=()=>{let im=new Image();im.onerror=reject;im.onload=()=>{let scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',quality))};im.src=r.result};r.readAsDataURL(file)})}
let pendingPlayers=[],pendingTeams=[];
async function prepareBulk(files,type){let pending=[],editor=$(type==='player'?'#playerImportEditor':'#teamImportEditor'),button=$(type==='player'?'#saveBulkPlayers':'#saveBulkTeams');editor.innerHTML='<p>Επεξεργασία φωτογραφιών…</p>';for(let f of [...files]){try{pending.push({name:'',img:await compressFile(f),filename:f.name.replace(/\.[^.]+$/,'').replace(/[-_]+/g,' ')})}catch(e){}}if(type==='player')pendingPlayers=pending;else pendingTeams=pending;renderPending(type);button.classList.toggle('hidden',!pending.length)}
function renderPending(type){let pending=type==='player'?pendingPlayers:pendingTeams,editor=$(type==='player'?'#playerImportEditor':'#teamImportEditor');editor.innerHTML='';pending.forEach((o,i)=>{let r=document.createElement('div');r.className='import-item';let im=document.createElement('img');im.src=o.img;let inp=document.createElement('input');inp.placeholder=type==='player'?'Όνομα ποδοσφαιριστή':'Όνομα ομάδας';inp.value=o.name||o.filename||'';inp.oninput=()=>o.name=inp.value;let del=document.createElement('button');del.type='button';del.textContent='Αφαίρεση';del.onclick=()=>{pending.splice(i,1);renderPending(type)};r.append(im,inp,del);editor.append(r)})}
$('#bulkPlayerPhotos').onchange=e=>prepareBulk(e.target.files,'player');$('#bulkTeamPhotos').onchange=e=>prepareBulk(e.target.files,'team');
function storeBulk(type){let pending=type==='player'?pendingPlayers:pendingTeams,key=type==='player'?'customPlayers':'customTeams',valid=pending.filter(x=>(x.name||x.filename).trim()).map(x=>({name:(x.name||x.filename).trim(),img:x.img}));if(!valid.length)return toast('Γράψε τουλάχιστον ένα όνομα');let before=d[key].length;d[key].push(...valid);try{save()}catch(e){d[key].splice(before);return toast('Οι φωτογραφίες είναι πολλές ή πολύ μεγάλες')}if(type==='player'){pendingPlayers=[];$('#bulkPlayerPhotos').value='';$('#saveBulkPlayers').classList.add('hidden');renderPending('player');playerBag=[]}else{pendingTeams=[];$('#bulkTeamPhotos').value='';$('#saveBulkTeams').classList.add('hidden');renderPending('team');teamBag=[]}toast('Αποθηκεύτηκαν '+valid.length+' εγγραφές')}
$('#saveBulkPlayers').onclick=()=>storeBulk('player');$('#saveBulkTeams').onclick=()=>storeBulk('team');
function renderCustom(){let e=$('#customList');if(!e)return;e.innerHTML='';[...d.customPlayers.map((x,i)=>({t:'Ποδοσφαιριστής',x,i,k:'customPlayers'})),...d.customTeams.map((x,i)=>({t:'Σήμα ομάδας',x,i,k:'customTeams'}))].forEach(o=>{let r=document.createElement('div');r.className='custom-row';let im=document.createElement('img');im.src=o.x.img;let inp=document.createElement('input');inp.className='edit-name';inp.value=o.x.name;inp.setAttribute('aria-label','Όνομα');let saveBtn=document.createElement('button');saveBtn.textContent='💾';saveBtn.title='Αποθήκευση ονόματος';saveBtn.onclick=()=>{let v=inp.value.trim();if(!v)return toast('Το όνομα δεν μπορεί να είναι κενό');o.x.name=v;save();toast('Το όνομα άλλαξε')};let replace=document.createElement('label');replace.textContent='📷';replace.title='Αλλαγή φωτογραφίας';replace.style.cursor='pointer';let fi=document.createElement('input');fi.type='file';fi.accept='image/*';fi.style.display='none';fi.onchange=async()=>{if(!fi.files[0])return;o.x.img=await compressFile(fi.files[0]);save();renderCustom();toast('Η φωτογραφία άλλαξε')};replace.append(fi);let del=document.createElement('button');del.textContent='🗑️';del.onclick=()=>{d[o.k].splice(o.i,1);save();renderCustom()};r.append(im,inp,saveBtn,replace,del);e.append(r)});if(!e.children.length)e.textContent='Δεν υπάρχουν δικές σου προσθήκες.'}

if("serviceWorker"in navigator)addEventListener("load",()=>navigator.serviceWorker.register("sw.js").catch(()=>{}));update();resetT();resetC();drawWheel();